name: Check Pull Requests

on:
  schedule:
    - cron: "* */1 * * *"  # Run every hour
  workflow_dispatch:        # Allow manual triggering

jobs:
  check_prs:
    runs-on: ubuntu-latest
    steps:
      - name: List Open Pull Requests
        id: list_prs
        uses: actions/github-script@v6
        with:
          script: |
            const { data: pullRequests } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            core.setOutput("prs", JSON.stringify(pullRequests.map(pr => pr.number)));

      - name: Filter PRs without Validated or InProgress Status
        id: filter_prs
        uses: actions/github-script@v6
        with:
          script: |
            const prs = JSON.parse(core.getInput("prs"));
            const prNumbers = [];
            for (const pr of prs) {
              const { data: statuses } = await github.rest.repos.listCommitStatusesForRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: pr.head.sha
              });
              const hasValidatedStatus = statuses.some(status => status.context === 'Validated');
              const hasInProgressStatus = statuses.some(status => status.context === 'InProgress');
              if (!hasValidatedStatus && !hasInProgressStatus) {
                prNumbers.push(pr.number);
              }
            }
            core.setOutput("prs_to_validate", JSON.stringify(prNumbers));

  trigger_validation:
    needs: check_prs
    if: needs.check_prs.outputs.prs_to_validate != '[]'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pr_number: ${{ fromJSON(needs.check_prs.outputs.prs_to_validate) }}

    steps:
      - name: Debug
        run: |
          echo "PR Number: ${{ matrix.pr_number }}"
