name: Check Pull Requests

on:
  schedule:
    - cron: "* */1 * * *"   # Run every hour
  workflow_dispatch:        # Allow manual triggering

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.result }}
    steps:
      - id: step1
        run: |
          echo "result=hello" >> $GITHUB_OUTPUT

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Job 1 output: ${{ needs.job1.outputs.output1 }}"

