name: Check Pull Requests

on:
  schedule:
    - cron: "* */1 * * *"   # Run every hour
  workflow_dispatch:        # Allow manual triggering

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Set Variable
        run: echo "MY_VARIABLE=my_value" >> $GITHUB_ENV #this is workflow scoped

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use Variable
        run: echo "$MY_VARIABLE"
