name: Validate Pull Request

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull Request number to validate"
        required: true
        type: number

jobs:
  validate_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Debug
        run: |
          echo "PR Number: ${{ github.event.inputs.pr_number }}"
