name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - "manifests/**" # Trigger only if changes are made in the 'manifests' folder

jobs:
  publish:
    if: true
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Publish
        uses: actions/checkout@v4
        with:
          path: ./
          repository: RestApia/RestApia.Extensions.Private
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}

      - name: Publish package
        run: |
          chmod +x ./build.sh
          ./build.sh Publish_HandlePush --PublishHeadCommit "${{ github.event.head_commit.message }}"
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
          PUBLISH_REPO_TOKEN: ${{ secrets.PUBLISH_REPO_TOKEN }}

      - name: Post Validation Success
        if: success()
        run: echo "Validation passed successfully."

      - name: Post Validation Failure
        if: failure()
        run: echo "Validation failed."
