name: Publish to GitHub Packages (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish package
        run: |
          chmod +x ./build.sh
          ./build.sh Publish_HandlePush
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
          PUBLISH_REPO_TOKEN: ${{ secrets.PUBLISH_REPO_TOKEN }}

      - name: Post Validation Success
        if: success()
        run: echo "Validation passed successfully."

      - name: Post Validation Failure
        if: failure()
        run: echo "Validation failed."